FROM python:3.9-slim

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir psycopg2-binary streamlit pandas plotly requests

WORKDIR /app

COPY shard-cli.py .
COPY rebalance.py .
COPY shard-stats.py .
COPY admin_dashboard.py .

RUN mkdir /files
COPY *.sql /files/

ENTRYPOINT ["python"]