CREATE ROLE rep_user WITH LOGIN REPLICATION PASSWORD 'rep_password';
GRANT CONNECT ON DATABASE traveler_api_db TO rep_user;
GRANT USAGE ON SCHEMA public TO rep_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO rep_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO rep_user;