-- Створення 16 баз даних
CREATE DATABASE db_0;
CREATE DATABASE db_1;
CREATE DATABASE db_2;
CREATE DATABASE db_3;
CREATE DATABASE db_4;
CREATE DATABASE db_5;
CREATE DATABASE db_6;
CREATE DATABASE db_7;
CREATE DATABASE db_8;
CREATE DATABASE db_9;
CREATE DATABASE db_a;
CREATE DATABASE db_b;
CREATE DATABASE db_c;
CREATE DATABASE db_d;
CREATE DATABASE db_e;
CREATE DATABASE db_f;